<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-29T11:48:39 IST" name="Default suite" finished-at="2024-08-29T11:48:47 IST" duration-ms="8034">
    <groups>
    </groups>
    <test started-at="2024-08-29T11:48:39 IST" name="Default test" finished-at="2024-08-29T11:48:47 IST" duration-ms="8034">
      <class name="DataDrivenTest.LoginTest">
        <test-method is-config="true" signature="LaunchBrowser()[pri:0, instance:DataDrivenTest.LoginTest@36fc695d]" started-at="2024-08-29T11:48:39 IST" name="LaunchBrowser" finished-at="2024-08-29T11:48:45 IST" duration-ms="5986" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchBrowser -->
        <test-method signature="LoginTest2(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:DataDrivenTest.LoginTest@36fc695d]" started-at="2024-08-29T11:48:45 IST" name="LoginTest2" data-provider="supplydata" finished-at="2024-08-29T11:48:47 IST" duration-ms="1680" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Marina]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Garita]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Maria@gemiw.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[23458679]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Maria@345]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[Maria@345]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at DataDrivenTest.LoginTest.LoginTest2(LoginTest.java:49)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest2 -->
        <test-method is-config="true" signature="CloseBrowser()[pri:0, instance:DataDrivenTest.LoginTest@36fc695d]" started-at="2024-08-29T11:48:47 IST" name="CloseBrowser" finished-at="2024-08-29T11:48:47 IST" duration-ms="289" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseBrowser -->
      </class> <!-- DataDrivenTest.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
